#!/bin/sh -l
# FILENAME: run-spectra-zb-dini

#SBATCH -A MTH250004
#SBATCH -p wholenode
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --time=02:30:00
#SBATCH --job-name spectra-zb-dini-gam-0
#SBATCH --mail-user=benjamin.hyatt@u.northwestern.edu
#SBATCH --mail-type=ALL

cd $SLURM_SUBMIT_DIR

module load anaconda/2024.02-py311

conda activate dedalus3

mpiexec python process_spectra_zb_dini.py --gamma=0

