#!/bin/sh -l
# FILENAME: run-disk-turb-inputs-gam-675

#SBATCH -A MTH250004
#SBATCH -p wholenode
#SBATCH --nodes=2
#SBATCH --ntasks=128
#SBATCH --time=48:00:00
#SBATCH --job-name disk-turb-gam-675-kf-20
#SBATCH --mail-user=benjamin.hyatt@u.northwestern.edu
#SBATCH --mail-type=ALL

cd $SLURM_SUBMIT_DIR

module load anaconda/2024.02-py311

conda activate dedalus3

mpiexec python disk_turb_run_inputs.py --gamma=675
